# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Fitnesshren' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyUtils', :git => 'https://github.com/tbaranes/SwiftyUtils.git', :commit => '982bffaadf8e831e75d3444dfba56af4d3962224'
  pod 'EZLoadingActivity', :git => 'https://github.com/hons82/EZLoadingActivity.git'
  pod 'Feathers'
  pod 'ISHPullUp'
  pod 'FeathersSwiftSocketIO'
end
